import mongoose from "mongoose";

const studentSchema = new mongoose.Schema({
    uid:{
        type:String,
        require:true
    },
    name:{
        type:String,
        require:true
    },
    academicLevel:{
        type:String,
        require:true
    },
    yearLevel:{
        type:String,
        require:true
    },
    semester:{
        type:String,
        require:true
    },
    gender:{
        type:String,
        require:true
    },
    payment:{
        type:String,
        require:true
    },
    program:{
        type:String,
        require:true
    },
    address:{
        type:String,
        require:true
    },
    contactNumber:{
        type:String,
        require:true
    },
    studentEmail:{
        type:String,
        require:true
    },
    aboutMe:{
        type:String,
        default:""
    },
    profileUrl:{
        type:String,
        default:""
    },
    paymentStatus:{
        type:String,
        default:""
    },
    hasOngoingPayment:{
        type:Boolean,
        default:false
    },
    discount:{
        hasDiscount:{
            type:Boolean,
            default:false
        },
        discountName:{
            type:String,
            default:""
        },
        discountFee:{
            type:Number,
            default:0
        },
        period:{
            type:String,
            default:""
        }
    }
});

export default mongoose.model("students", studentSchema)